= Micrometer RedisTimeSeries
:linkattrs:
:project-owner:   redis-developer
:project-name:    micrometer-redistimeseries
:project-group:   com.redis
:project-version: 0.3.4
:project-url:     https://github.com/{project-owner}/{project-name}
:product-name:    Micrometer RedisTimeSeries
:artifact-id:     micrometer-registry-redistimeseries

image:https://github.com/{project-owner}/{project-name}/actions/workflows/early-access.yml/badge.svg["Build Status", link="https://github.com/{project-owner}/{project-name}/actions/workflows/early-access.yml"]
image:https://img.shields.io/maven-central/v/{project-group}/{artifact-id}[Download, link="https://search.maven.org/#search|ga|1|{artifact-id}"]
image:https://img.shields.io/nexus/s/{project-group}/{artifact-id}?server=https%3A%2F%2Fs01.oss.sonatype.org[Snapshot,link="https://s01.oss.sonatype.org/#nexus-search;quick~{artifact-id}"]
image:https://codecov.io/gh/{project-owner}/{project-name}/branch/master/graph/badge.svg["Coverage", link="https://codecov.io/gh/{project-owner}/{project-name}"]

{product-name} is a https://micrometer.io[Micrometer] registry for sending metrics to https://redis.io/docs/stack/timeseries/[RedisTimeSeries].

This registry can be used in any application that uses Micrometer for recording metrics.

== Getting Started

Add {artifact-id} to your application dependencies:

.Maven
[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>{project-group}</groupId>
    <artifactId>{artifact-id}</artifactId>
    <version>{project-version}</version>
</dependency>
----

.Gradle
[source,groovy,subs="verbatim,attributes"]
----
dependencies {
    implementation '{project-group}:{artifact-id}:{project-version}'
}
----

== Usage

[source,java]
----
RedisTimeSeriesConfig config = new RedisTimeSeriesConfig() { // <1>

	@Override
	public String get(String key) {
		return null;
	}

	@Override
	public String uri() {
		return "redis://example.redis.cloud:12000";
	}
	
};
MeterRegistry registry = new RedisTimeSeriesMeterRegistry(config, Clock.SYSTEM); // <2>
Timer timer = registry.timer("mytimer"); // <3>
timer.record(() -> doSomeWork()); // <4>
----

<1> Create a config object
<2> Instantiate a `MeterRegistry` with the previously created config
<3> Register a meter
<4> Instrument a part of your application using the meter

== Configuration

The following properties can be used to specify how the registry connects to Redis.

=== `uri`

* Type: `string`
* *Required*

Connect to a Redis Cluster.


Redis URI for your Redis instance, for example:
----
redis://example.redis.cloud:6379
----

See https://github.com/lettuce-io/lettuce-core/wiki/Redis-URI-and-connection-details#uri-syntax[Lettuce's URI syntax] for all of the possible URI parameters you can use here.

=== `cluster`

* Type: `boolean`
* Default value: `false`

Connect to a Redis Cluster.

=== `poolSize`

* Type: `integer`
* Default value: `8`

Maximum number of connections that can be allocated by the pool at a given time.
Use a negative value for no limit.

=== `keyspace`

* Type: `string`
* Default value: `null` (no keyspace prefix)

Prefix for all Redis keys used by {product-name}.
